1_if1.py completed
GXLDSTEIN/learn-homework-1 pull request #1
Opened 2023-11-22 15:59 UTC by GXLDSTEIN

2023-11-23 09:45 UTC, Chyrets requested changes

2023-11-23 09:45 UTC, Chyrets commented on 1_if1.py
> +        if age < 0:
здесь ты можешь объединить два условия в одно 0 < age < 150

2023-11-23 09:45 UTC, Chyrets commented on 1_if1.py
> +            print("Попробуйте ещё раз.")
а вот тут не хвататет continue, без него получается, что можно ввести возрас больше 150

2023-11-24 06:34 UTC, GXLDSTEIN commented on 1_if1.py
> +            print("Попробуйте ещё раз.")
разве цикл и без continue не пойдёт на следующую итерацию? break же только в ветке else у этого условия

2023-11-24 07:08 UTC, Chyrets requested changes

2023-11-24 07:08 UTC, Chyrets commented on 1_if1.py
> +            print("Попробуйте ещё раз.")
да, пойдет, но тут нарушается один из принципов питона: Explicit is better than implicit. В первом случае у тебя явно указанно, что надо пойти на новую итерацию, а во втром нет

2023-11-29 10:24 UTC, Chyrets commented on 3_for.py
> +        m = mean(phone["items_sold"])
неплохо, функции из стандартной библиотеки зачастую быстрее работают чем питоновский код

2023-11-29 10:24 UTC, Chyrets commented on 5_while2.py
> +                print("sorry, try again")
в питоне можно делать больше одного блока except, я бы тут на твоем месте вложенный try/except блок убрал и except KeyError вынес в первый блок

2023-12-05 05:08 UTC, merged